Add support for Addyi, a medication that does not have ETASU
mcode/rems-admin pull request #136
Opened 2024-03-06 04:36 UTC by plarocque4

## Describe your changes

Add support for Addyi, a medication that does not have ETASU and only has a medication guide.

## Issue ticket number and Jira link

[REMS-616](https://jira.mitre.org/browse/REMS-616)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

## Checklist for conducting a review
- [ ] Review the code changes and make sure they all make sense and are necessary. 
- [ ] Pull the PR branch locally and test by running through workflow and making sure everything works as it is supposed to. 

## Workflow 

Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your Pull Request for you.

2024-03-07 23:16 UTC, jtquach1 requested changes

2024-03-14 00:35 UTC, plarocque4 commented on src/hooks/hookResources.ts
> +              smartLinkCount++;
I implemented something similar

2024-03-14 00:35 UTC, plarocque4 commented on src/hooks/hookResources.ts
> +        let smartLinkCountAdded = 0;
I implemented something similar

2024-03-19 14:43 UTC, avirgulto approved these changes
Worked as expected for Addyi, code looks good

2024-03-19 14:50 UTC, merged